"""employee

Revision ID: 61e5c8c02c6f
Revises: 71bad533ab7f
Create Date: 2024-06-01 00:57:09.805943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e5c8c02c6f'
down_revision: Union[str, None] = '71bad533ab7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'video', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'employee_id')
    # ### end Alembic commands ###
