"""employee

Revision ID: 71bad533ab7f
Revises: d12d58490a36
Create Date: 2024-06-01 00:49:24.128753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bad533ab7f'
down_revision: Union[str, None] = 'd12d58490a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_violation', sa.Column('is_spectated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_violation', 'is_spectated')
    # ### end Alembic commands ###
