"""video bd renamed column

Revision ID: cd468c76fcd3
Revises: 2c6100c16a5c
Create Date: 2024-05-31 16:24:18.246680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd468c76fcd3'
down_revision: Union[str, None] = '2c6100c16a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('video', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('video', 'title')
    # ### end Alembic commands ###
